eWords = [
  "eager", "eagle", "ear", "earache", "earl", "early", "earn", "earnest",
  "earring", "earth", "earthquake", "earthy", "ease", "easel", "easily",
  "east", "eastern", "easy", "eat", "eaten", "eater", "eaves", "ebb",
  "ebony", "eccentric", "echo", "eclipse", "ecology", "economic",
  "economy", "ecosystem", "ecstasy", "eddy", "edge", "edgy", "edible",
  "edit", "edition", "editor", "educate", "education", "eel", "eerie",
  "effect", "effective", "efficient", "effort", "effortless", "egg",
  "eggplant", "ego", "eight", "eighteen", "eighty", "either", "eject",
  "elaborate", "elastic", "elbow", "elder", "elderly", "elect",
  "election", "electric", "electron", "elegant", "element", "elephant",
  "elevate", "elevator", "eleven", "eligible", "eliminate", "elite",
  "elk", "ellipse", "elm", "elope", "eloquent", "else", "elsewhere",
  "elude", "elusive", "email", "embark", "embarrass", "ember",
  "embrace", "embroider", "emerald", "emerge", "emergency", "emit",
  "emotion", "emotional", "empathy", "emperor", "emphasis", "empire",
  "employ", "employee", "employer", "empower", "empty", "enable",
  "enact", "enchant", "encircle", "enclose", "encounter", "encourage",
  "encrypt", "end", "endanger", "endless", "endorse", "endure",
  "enemy", "energy", "enforce", "engage", "engine", "engineer",
  "english", "engrave", "enhance", "enjoy", "enlarge", "enlighten",
  "enormous", "enough", "enrich", "enroll", "ensure", "enter",
  "enterprise", "entertain", "enthusiasm", "entire", "entrance",
  "entry", "envelope", "envious", "environment", "envy", "epic",
  "episode", "equal", "equality", "equation", "equator", "equip",
  "equipment", "era", "erase", "eraser", "erect", "erode", "erosion",
  "errand", "erratic", "error", "erupt", "escalate", "escape",
  "escort", "especially", "essay", "essence", "essential",
  "establish", "estate", "esteem", "estimate", "etch", "eternal",
  "ethical", "ethics", "ethnic", "evacuate", "evade", "evaluate",
  "evaporate", "eve", "even", "evening", "event", "eventual",
  "ever", "evergreen", "everlasting", "every", "everybody",
  "everyday", "everyone", "everything", "everywhere", "evidence",
  "evident", "evil", "evoke", "evolution", "evolve", "exact",
  "exaggerate", "exam", "examine", "example", "exceed", "excel",
  "excellent", "except", "exception", "excerpt", "excess",
  "exchange", "excite", "exclaim", "exclude", "exclusive", "excuse",
  "execute", "exempt", "exercise", "exert", "exhale", "exhaust",
  "exhibit", "exile", "exist", "exit", "exotic", "expand", "expect",
  "expedition", "expel", "expend", "expense", "expensive",
  "experience", "experiment", "expert", "expire", "explain",
  "explode", "exploit", "explore", "explosion", "export", "expose",
  "express", "expression", "exquisite", "extend", "extensive",
  "extent", "exterior", "external", "extinct", "extra", "extract",
  "extraordinary", "extreme", "eye", "eyebrow", "eyelash", "eyelid",
];
